import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
// import Example from "../components/Example";
import { useEffect } from "react";
import dynamic from "next/dynamic";

const Example = dynamic(() => import("../components/Example"), {
  ssr: false,
});

export default function Home() {
  // useEffect(() => {
  //   const Example = import("../components/Example");
  // }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Example placeholder="noi dung " />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
